server:
  port: 7001

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

logging:
  level:
    root: info
    de.shinythings: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug

debug: true

---
spring:
  profiles: docker

spring.data:
  mongodb:
    host: mongodb

server:
  port: 8080
