server:
  port: 7000

app:
  product-service:
    host: localhost
    port: 7001
    https: false
  recommendation-service:
    host: localhost
    port: 7002
    https: false
  review-service:
    host: localhost
    port: 7003
    https: false

logging:
  level:
    root: INFO
    de.shinythings: DEBUG

---
spring:
  profiles: docker

server:
  port: 8080

app:
  product-service:
    host: product
    port: 8080
    https: false
  recommendation-service:
    host: recommendation
    port: 8080
    https: false
  review-service:
    host: review
    port: 8080
    https: false
